const SERVICOS={banho:{label:"Banho",duracao:1},banho_tosa:{label:"Banho e Tosa",duracao:2}};
const FUSO="America/Sao_Paulo",$=id=>document.getElementById(id),pad=n=>String(n).padStart(2,"0");
const configurado=Boolean(window.SUPABASE_URL&&window.SUPABASE_KEY&&!window.SUPABASE_URL.startsWith("COLE_")&&window.supabase);
function apiSupabase(){const db=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_KEY);const ok=({data,error})=>{if(error)throw new Error(error.message);return data||[]};return{listarTutores:async()=>ok(await db.from("tutor").select("id_tutor,nome,cpf,telefone").order("nome")),criarTutor:async x=>ok(await db.from("tutor").insert([x]).select()),listarPets:async()=>ok(await db.from("pet").select("id_pet,nome,especie,raca,id_tutor,tutor(nome)").order("nome")),criarPet:async x=>ok(await db.from("pet").insert([x]).select()),listarAgendamentos:async()=>ok(await db.from("agendamento").select("id_agendamento,data_hora,status,servico,id_pet,pet(nome,especie,raca,tutor(nome))").order("data_hora")),criarAgendamento:async x=>ok(await db.from("agendamento").insert([x]).select()),atualizarAgendamento:async(id,x)=>ok(await db.from("agendamento").update(x).eq("id_agendamento",id).select())}}
function apiLocal(){const K="petshop-agenda-local",v=()=>({tutor:[],pet:[],agendamento:[],seq:0}),ler=()=>{try{return JSON.parse(localStorage.getItem(K))||v()}catch{return v()}},salvar=d=>localStorage.setItem(K,JSON.stringify(d));return{listarTutores:async()=>ler().tutor,criarTutor:async x=>{const d=ler();d.tutor.push({id_tutor:++d.seq,...x});salvar(d)},listarPets:async()=>{const d=ler();return d.pet.map(p=>({...p,tutor:d.tutor.find(t=>t.id_tutor===p.id_tutor)}))},criarPet:async x=>{const d=ler();d.pet.push({id_pet:++d.seq,...x,id_tutor:Number(x.id_tutor)});salvar(d)},listarAgendamentos:async()=>{const d=ler();return d.agendamento.map(a=>{const p=d.pet.find(x=>x.id_pet===a.id_pet);return{...a,pet:p?{...p,tutor:d.tutor.find(t=>t.id_tutor===p.id_tutor)}:null}})},criarAgendamento:async x=>{const d=ler();d.agendamento.push({id_agendamento:++d.seq,...x,id_pet:Number(x.id_pet),status:"agendado"});salvar(d)},atualizarAgendamento:async(id,x)=>{const d=ler(),a=d.agendamento.find(x=>x.id_agendamento===Number(id));Object.assign(a,x);salvar(d)}}}
const api=configurado?apiSupabase():apiLocal();let tutores=[],pets=[],agendamentos=[],idReagendar=null;
function partes(v){return Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:FUSO,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hourCycle:"h23"}).formatToParts(new Date(v)).map(p=>[p.type,p.value]))}function diaBR(v){const p=partes(v);return`${p.year}-${p.month}-${p.day}`}function horaBR(v){return Number(partes(v).hour)}function exibir(v){return new Intl.DateTimeFormat("pt-BR",{timeZone:FUSO,dateStyle:"short",timeStyle:"short"}).format(new Date(v))}
function iso(d,h){return `${d}T${h}:00`}
function hoje(){const p=partes(new Date());return`${p.year}-${p.month}-${p.day}`}function norm(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
let timer;function aviso(m,e=false){const t=$("toast");t.textContent=m;t.className="toast"+(e?" erro":"");t.hidden=false;clearTimeout(timer);timer=setTimeout(()=>t.hidden=true,3000)}async function acao(form,fn){const b=form.querySelector('button[type="submit"]');b.disabled=true;try{await fn()}catch(e){console.error(e);aviso(e.message,true)}finally{b.disabled=false}}
function select(el,texto,dados,val,rot){el.innerHTML="";el.add(new Option(texto,""));dados.forEach(x=>el.add(new Option(rot(x),val(x))))}
function filtrarPets(){const q=norm($("pesquisa-pet").value),r=pets.filter(p=>!q||norm(`${p.nome} ${p.tutor?.nome} ${p.raca} ${p.especie}`).includes(q));select($("agendamento-pet"),r.length?"Selecione o pet":"Nenhum cadastro encontrado",r,p=>p.id_pet,p=>`${p.nome}${p.raca?" - "+p.raca:""} (tutor: ${p.tutor?.nome||"?"})`);$("pesquisa-pet-info").textContent=q?`${r.length} cadastro(s) encontrado(s).`:"Digite acima para encontrar o cadastro rapidamente."}
function resumo(){$("stat-tutores").textContent=tutores.length;$("stat-pets").textContent=pets.length;$("stat-hoje").textContent=agendamentos.filter(a=>a.status==="agendado"&&diaBR(a.data_hora)===hoje()).length;$("stat-agendados").textContent=agendamentos.filter(a=>a.status==="agendado").length}
async function carregarTutores(){tutores=await api.listarTutores();select($("pet-tutor"),tutores.length?"Selecione o tutor":"Cadastre um tutor primeiro",tutores,t=>t.id_tutor,t=>t.nome);resumo()}async function carregarPets(){pets=await api.listarPets();filtrarPets();resumo()}async function carregarAgenda(){agendamentos=await api.listarAgendamentos();render();resumo()}
function ocupados(dia,ignorar){const s=new Set();agendamentos.filter(a=>a.status==="agendado"&&String(a.id_agendamento)!==String(ignorar)&&diaBR(a.data_hora)===dia).forEach(a=>{for(let k=0;k<(SERVICOS[a.servico]?.duracao||1);k++)s.add(`${pad(horaBR(a.data_hora)+k)}:00`)});return s}function horarios(el,dia,serv,ignorar){el.innerHTML='<option value="">Selecione o horário</option>';if(!dia)return;const dur=SERVICOS[serv]?.duracao||1,o=ocupados(dia,ignorar),agora=new Date(),p=partes(agora),diaAtual=`${p.year}-${p.month}-${p.day}`,horaAtual=Number(p.hour),minutoAtual=Number(new Intl.DateTimeFormat("en-CA",{timeZone:FUSO,minute:"2-digit"}).format(agora));for(let h=8;h<=18-dur;h++){if(dia===diaAtual&&(h<horaAtual||(h===horaAtual&&minutoAtual>0)))continue;let livre=true;for(let k=0;k<dur;k++)if(o.has(`${pad(h+k)}:00`))livre=false;if(livre)el.add(new Option(`${pad(h)}:00`,`${pad(h)}:00`))}if(el.options.length===1)el.options[0].textContent="Nenhum horário disponível"}
function render(){const lista=agendamentos.filter(a=>$("filtro-status").value==="todos"||a.status===$("filtro-status").value);$("tabela-agendamentos").querySelector("tbody").innerHTML=lista.map(a=>`<tr><td data-label="Pet">🐾 ${esc(a.pet?.nome||"?")}</td><td data-label="Tutor">${esc(a.pet?.tutor?.nome||"?")}</td><td data-label="Serviço">${SERVICOS[a.servico]?.label||"Banho"}</td><td data-label="Data/Hora">${exibir(a.data_hora)}</td><td data-label="Status"><span class="badge badge-${a.status}">${a.status}</span></td><td class="acoes-cell"><div class="acoes">${a.status==="agendado"?`<button class="btn-reagendar" data-id="${a.id_agendamento}">Reagendar</button><button class="btn-concluir" data-id="${a.id_agendamento}">Concluir</button><button class="btn-cancelar" data-id="${a.id_agendamento}">Cancelar</button>`:""}</div></td></tr>`).join("");$("vazio").hidden=lista.length>0;document.querySelectorAll(".btn-concluir,.btn-cancelar").forEach(b=>b.onclick=async()=>{const status=b.classList.contains("btn-cancelar")?"cancelado":"concluido";if(status==="cancelado"&&!confirm("Cancelar este agendamento?"))return;await api.atualizarAgendamento(b.dataset.id,{status});await carregarAgenda()});document.querySelectorAll(".btn-reagendar").forEach(b=>b.onclick=()=>abrir(agendamentos.find(a=>String(a.id_agendamento)===b.dataset.id)))}
function abrir(a){idReagendar=a.id_agendamento;$("reagendar-info").textContent=`${a.pet?.nome||"Pet"} - atual: ${exibir(a.data_hora)}`;$("reagendar-dia").value=diaBR(a.data_hora);horarios($("reagendar-hora"),diaBR(a.data_hora),a.servico,a.id_agendamento);$("reagendar-hora").value=`${pad(horaBR(a.data_hora))}:00`;$("modal").hidden=false}
$("pesquisa-pet").oninput=filtrarPets;$("agendamento-dia").onchange=()=>horarios($("agendamento-hora"),$("agendamento-dia").value,$("agendamento-servico").value);$("agendamento-servico").onchange=$("agendamento-dia").onchange;$("filtro-status").onchange=render;
document.querySelectorAll(".tab-btn").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab-btn").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("painel-cadastros").hidden=b.dataset.tab!=="cadastros";$("painel-agenda").hidden=b.dataset.tab!=="agenda"});
$("tutor-cpf").oninput=e=>{let v=e.target.value.replace(/\D/g,"").slice(0,11);e.target.value=v.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,"$1.$2.$3-$4")};
$("form-tutor").onsubmit=e=>{e.preventDefault();acao(e.target,async()=>{await api.criarTutor({nome:$("tutor-nome").value.trim(),cpf:$("tutor-cpf").value.replace(/\D/g,""),telefone:$("tutor-telefone").value.trim()||null});e.target.reset();await carregarTutores();aviso("Tutor cadastrado!")})};
$("form-pet").onsubmit=e=>{e.preventDefault();acao(e.target,async()=>{await api.criarPet({id_tutor:Number($("pet-tutor").value),nome:$("pet-nome").value.trim(),especie:$("pet-especie").value.trim(),raca:$("pet-raca").value.trim()||null});e.target.reset();await carregarPets();aviso("Pet cadastrado!")})};
$("form-agendamento").onsubmit=e=>{e.preventDefault();acao(e.target,async()=>{await api.criarAgendamento({id_pet:Number($("agendamento-pet").value),servico:$("agendamento-servico").value,data_hora:iso($("agendamento-dia").value,$("agendamento-hora").value)});e.target.reset();$("pesquisa-pet").value="";filtrarPets();await carregarAgenda();aviso("Agendamento realizado!")})};
$("reagendar-cancelar").onclick=()=>$("modal").hidden=true;$("reagendar-dia").onchange=()=>{const a=agendamentos.find(x=>String(x.id_agendamento)===String(idReagendar));horarios($("reagendar-hora"),$("reagendar-dia").value,a.servico,idReagendar)};$("form-reagendar").onsubmit=e=>{e.preventDefault();acao(e.target,async()=>{await api.atualizarAgendamento(idReagendar,{data_hora:iso($("reagendar-dia").value,$("reagendar-hora").value)});$("modal").hidden=true;await carregarAgenda();aviso("Agendamento reagendado!")})};
function normalizarCadastro(v){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function cpfExibicao(v){const n=String(v??"").replace(/\D/g,"");return n.length===11?n.replace(/(\d{3})(\d{3})(\d{3})(\d{2})/,"$1.$2.$3-$4"):n}
function renderCadastros(){const campo=$("pesquisa-cadastros"),filtro=$("tipo-cadastro"),lista=$("lista-cadastros"),contagem=$("resultado-contagem"),vazio=$("cadastros-vazio");if(!campo||!filtro||!lista)return;const termo=normalizarCadastro(campo.value.trim());if(!termo){lista.innerHTML="";lista.hidden=true;vazio.hidden=true;contagem.textContent="Digite algo para pesquisar um cadastro.";return}const resultados=[];if(filtro.value==="todos"||filtro.value==="tutores")tutores.forEach(t=>{if(normalizarCadastro(`${t.nome} ${t.cpf??""} ${t.telefone??""}`).includes(termo))resultados.push({tipo:"Tutor",nome:t.nome,detalhe:`CPF: ${cpfExibicao(t.cpf)||"não informado"} | Telefone: ${t.telefone||"não informado"}`})});if(filtro.value==="todos"||filtro.value==="pets")pets.forEach(p=>{if(normalizarCadastro(`${p.nome} ${p.especie} ${p.raca??""} ${p.tutor?.nome??""}`).includes(termo))resultados.push({tipo:"Pet",nome:p.nome,detalhe:`${p.especie}${p.raca?" | Raça: "+p.raca:""} | Tutor: ${p.tutor?.nome??"não encontrado"}`})});lista.innerHTML=resultados.map(r=>`<div class="item-cadastro"><strong>${esc(r.tipo)}: ${esc(r.nome)}</strong><small>${esc(r.detalhe)}</small></div>`).join("");lista.hidden=resultados.length===0;vazio.hidden=resultados.length>0;contagem.textContent=`${resultados.length} cadastro(s) encontrado(s).`}
$("pesquisa-cadastros").oninput=renderCadastros;$("tipo-cadastro").onchange=renderCadastros;
(async()=>{$("modo").textContent=configurado?"":"⚠️ Modo teste: dados salvos neste navegador.";$("agendamento-dia").min=hoje();$("reagendar-dia").min=hoje();await carregarTutores();await carregarPets();await carregarAgenda()})();
